repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2 # Use a specific tag/commit for stability
    hooks:
      - id: black
        language_version: python3 # Specify python version if needed

  - repo: https://github.com/astral-sh/ruff-pre-commit # Updated repo URL
    # Find the latest tag via https://github.com/astral-sh/ruff-pre-commit/releases
    rev: v0.5.1 # Use a specific tag/commit
    hooks:
      # Run the formatter.
      - id: ruff-format
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix] # Fix automatically and fail if fixes were made

# Temporarily removed pytest hook due to persistent ModuleNotFoundError
# Investigate integration separately (e.g., tox, wrapper script, conftest adjustments)
#  - repo: local
#    hooks:
#      - id: pytest
#        name: pytest
#        entry: python -m pytest -q -x --asyncio-mode=auto tests/unit/
#        language: python
#        language_version: python3.10
#        additional_dependencies: [
#            "pytest>=8.3.5",
#            "pytest-asyncio>=0.26.0",
#            # Install local package *with* dev dependencies
#            ".[dev]", 
#        ]
#        types: [python]
#        pass_filenames: false
#        always_run: true 