# .pre-commit-config.yaml
# Use tox to manage linting and testing environments

# Optional: Specify minimum pre-commit version
# min_version: 2.1.0

repos:
  - repo: local
    hooks:
      - id: tox
        name: Run linters and tests via tox
        entry: tox -e lint,test
        language: python # Use python environment for the hook
        language_version: python3.10 # Match project version
        additional_dependencies: ["tox>=4.0.0"] # tox itself is needed
        types: [python]
        pass_filenames: false

# Removed previous hooks for black, ruff, pytest as they are now handled by tox 