# Execution Status Constants
STATUS_SUCCESS = "success"
STATUS_ERROR = "error"
STATUS_MAX_ITERATIONS = "max_iterations_reached"
STATUS_TIMEOUT = "timeout"
STATUS_NOT_FOUND = "not_found"
STATUS_NOT_ALLOWED = "not_allowed"

# Execution Reason Constants (for errors or specific outcomes)
REASON_UNKNOWN = "unknown"
REASON_LLM_ERROR = "llm_error"
REASON_LLM_PROCESSING_ERROR = "llm_processing_unexpected_error"
REASON_PROMPT_BUILD_FAILED = "prompt_build_failed"
REASON_FRAGMENT_NOT_FOUND = "fragment_not_found_or_invalid"
REASON_ACTION_FAILED = "action_failed"
REASON_ACTION_NOT_FOUND = "action_not_found"
REASON_ACTION_NOT_ALLOWED = "action_not_allowed"
REASON_NO_ALLOWED_SKILLS = "no_allowed_skills"
REASON_INVALID_INPUT = "invalid_input"
REASON_NO_ACTION_LOOP = "no_action_loop"
REASON_MAX_ITERATIONS = "max_iterations_reached"
REASON_TIMEOUT = "timeout_reached"
REASON_EXECUTOR_CALL_FAILED = "executor_call_failed"
REASON_DELEGATION_FAILED = "delegation_failed"
REASON_FRAGMENT_FAILED = "fragment_failed"
REASON_MAX_STEPS_REACHED = "max_steps_reached"
REASON_ORCHESTRATION_CRITICAL_ERROR = "orchestration_critical_error" 