# Execution Status Constants
STATUS_SUCCESS = "success"
STATUS_ERROR = "error"
STATUS_MAX_ITERATIONS = "max_iterations_reached"
STATUS_TIMEOUT = "timeout"
STATUS_NOT_FOUND = "not_found"
STATUS_NOT_ALLOWED = "not_allowed"

# Execution Reason Constants (for errors or specific outcomes)
REASON_SUCCESS = "Operation completed successfully."
REASON_UNKNOWN = "Reason unknown."
REASON_INVALID_INPUT = "Input data was invalid or incomplete."
REASON_LLM_ERROR = "LLM call failed or returned invalid format."
REASON_TOOL_ERROR = "A tool execution failed."
REASON_PLAN_FAILURE = "Could not generate a valid plan."
REASON_MAX_STEPS_REACHED = "Maximum execution steps reached."
REASON_ORCHESTRATION_CRITICAL_ERROR = "A critical error occurred in the orchestrator."
REASON_EXECUTOR_CALL_FAILED = "Call to FragmentExecutor failed."
REASON_DELEGATION_FAILED = "LLM failed to delegate to a valid component."
REASON_FRAGMENT_FAILED = "A fragment execution reported failure."
REASON_NO_ALLOWED_SKILLS = "No skills were allowed or available for the fragment."
REASON_FRAGMENT_NOT_FOUND = "Fragment specified for execution not found in registry."
REASON_SETUP_ERROR = "An error occurred during component setup or configuration."
REASON_PROMPT_BUILD_FAILED = "Failed to build the prompt for the LLM."
REASON_LLM_PROCESSING_ERROR = "Error processing the LLM response structure."
REASON_ACTION_FAILED = "action_failed"
REASON_ACTION_NOT_FOUND = "action_not_found"
REASON_ACTION_NOT_ALLOWED = "action_not_allowed"
REASON_NO_ACTION_LOOP = "no_action_loop"
REASON_MAX_ITERATIONS = "max_iterations_reached"
REASON_TIMEOUT = "timeout_reached"
REASON_DELEGATION_FAILED = "delegation_failed"
REASON_FRAGMENT_FAILED = "fragment_failed"
REASON_MAX_STEPS_REACHED = "max_steps_reached"
REASON_ORCHESTRATION_CRITICAL_ERROR = "orchestration_critical_error"
